### ISSUE TITLE
Can't get visualisation to work

### ISSUE THREAD

**Issue by mcromb** [Suyash458/SoftwareOscilloscope#5]
Probably a very simple issue but ive not used pyqtgraph before so don't know why when i run the test code (with socketplot-test running in the background) nothing appears - no window is shown.

I have PyQt5 so i have used the updated pyqt5 code in the pull requests

**Comment by suyashb95** [comment]
Interesting, lemme have a look. Thanks for pointing out!

**Comment by mcromb** [comment]
thanks! i am using spyder and python 2.7 if thats useful information

**Comment by mcromb** [comment]
Oh hang on, it is working now! I'm not sure why it wasn't before...
Possibly it was because i was accidentally tried to run SoftwareOscilloscope.py before running the test code

**Comment by suyashb95** [comment]
Oh nice, I was thinking it could be an issue with the interactive console not being able to render Qt windows. If you're plotting data from a serial port, [this project](https://x-io.co.uk/serial-oscilloscope/) might be useful too
